spring:
  redis:
#    cluster:
#      nodes: 192.168.25.133:7001,192.168.25.134:7002,192.168.25.135:7003
#      password: 123
    host: 192.168.25.133
    port: 6379
    lettuce:
      pool:
        # 最大活跃连接数，负数为不限制
        max-active: 500
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1ms
        # 最大空闲连接数
        max-idle: 100
        min-idle: 20
        # 最小空闲连接数