spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=yes&characterEncode=UTF-8&useSSL=true
    username: root
    password: corner666
    driver-class-name: com.mysql.jdbc.Driver
    # 数据源类型：Druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat, wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  redis:
#    cluster:
#      nodes: 192.168.25.133:7001,192.168.25.134:7002,192.168.25.135:7003
#      password: 123
    host: 192.168.25.133
    port: 6379
    lettuce:
      pool:
        # 最大活跃连接数，负数为不限制
        max-active: 500
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1ms
        # 最大空闲连接数
        max-idle: 100
        min-idle: 20
        # 最小空闲连接数
  rabbitmq:
    host: 192.168.25.133
    port: 5672  
    username: admin  
    password: 123        
mybatis:
  mapper-locations: classpath*:sqlmap/**/*.xml
  type-aliases-package: com.corner.eshop.product.entity